#import <UIKit/UIKit.h>

//! Project version number for GPUImageFramework.
FOUNDATION_EXPORT double GPUImageFrameworkVersionNumber;

//! Project version string for GPUImageFramework.
FOUNDATION_EXPORT const unsigned char GPUImageFrameworkVersionString[];

#import <MTGPUImage/GLProgram.h>

// Base classes
#import <MTGPUImage/GPUImageContext.h>
#import <MTGPUImage/GPUImageOutput.h>
#import <MTGPUImage/GPUImageView.h>
#import <MTGPUImage/GPUImageVideoCamera.h>
#import <MTGPUImage/GPUImageStillCamera.h>
#import <MTGPUImage/GPUImageMovie.h>
#import <MTGPUImage/GPUImagePicture.h>
#import <MTGPUImage/GPUImageRawDataInput.h>
#import <MTGPUImage/GPUImageRawDataOutput.h>
#import <MTGPUImage/GPUImageMovieWriter.h>
#import <MTGPUImage/GPUImageFilterPipeline.h>
#import <MTGPUImage/GPUImageTextureOutput.h>
#import <MTGPUImage/GPUImageFilterGroup.h>
#import <MTGPUImage/GPUImageTextureInput.h>
#import <MTGPUImage/GPUImageUIElement.h>
#import <MTGPUImage/GPUImageBuffer.h>
#import <MTGPUImage/GPUImageFramebuffer.h>
#import <MTGPUImage/GPUImageFramebufferCache.h>

// Filters
#import <MTGPUImage/GPUImageFilter.h>
#import <MTGPUImage/GPUImageTwoInputFilter.h>
#import <MTGPUImage/GPUImagePixellateFilter.h>
#import <MTGPUImage/GPUImagePixellatePositionFilter.h>
#import <MTGPUImage/GPUImageSepiaFilter.h>
#import <MTGPUImage/GPUImageColorInvertFilter.h>
#import <MTGPUImage/GPUImageSaturationFilter.h>
#import <MTGPUImage/GPUImageContrastFilter.h>
#import <MTGPUImage/GPUImageExposureFilter.h>
#import <MTGPUImage/GPUImageBrightnessFilter.h>
#import <MTGPUImage/GPUImageLevelsFilter.h>
#import <MTGPUImage/GPUImageSharpenFilter.h>
#import <MTGPUImage/GPUImageGammaFilter.h>
#import <MTGPUImage/GPUImageSobelEdgeDetectionFilter.h>
#import <MTGPUImage/GPUImageSketchFilter.h>
#import <MTGPUImage/GPUImageToonFilter.h>
#import <MTGPUImage/GPUImageSmoothToonFilter.h>
#import <MTGPUImage/GPUImageMultiplyBlendFilter.h>
#import <MTGPUImage/GPUImageDissolveBlendFilter.h>
#import <MTGPUImage/GPUImageKuwaharaFilter.h>
#import <MTGPUImage/GPUImageKuwaharaRadius3Filter.h>
#import <MTGPUImage/GPUImageVignetteFilter.h>
#import <MTGPUImage/GPUImageGaussianBlurFilter.h>
#import <MTGPUImage/GPUImageGaussianBlurPositionFilter.h>
#import <MTGPUImage/GPUImageGaussianSelectiveBlurFilter.h>
#import <MTGPUImage/GPUImageOverlayBlendFilter.h>
#import <MTGPUImage/GPUImageDarkenBlendFilter.h>
#import <MTGPUImage/GPUImageLightenBlendFilter.h>
#import <MTGPUImage/GPUImageSwirlFilter.h>
#import <MTGPUImage/GPUImageSourceOverBlendFilter.h>
#import <MTGPUImage/GPUImageColorBurnBlendFilter.h>
#import <MTGPUImage/GPUImageColorDodgeBlendFilter.h>
#import <MTGPUImage/GPUImageScreenBlendFilter.h>
#import <MTGPUImage/GPUImageExclusionBlendFilter.h>
#import <MTGPUImage/GPUImageDifferenceBlendFilter.h>
#import <MTGPUImage/GPUImageSubtractBlendFilter.h>
#import <MTGPUImage/GPUImageHardLightBlendFilter.h>
#import <MTGPUImage/GPUImageSoftLightBlendFilter.h>
#import <MTGPUImage/GPUImageColorBlendFilter.h>
#import <MTGPUImage/GPUImageHueBlendFilter.h>
#import <MTGPUImage/GPUImageSaturationBlendFilter.h>
#import <MTGPUImage/GPUImageLuminosityBlendFilter.h>
#import <MTGPUImage/GPUImageCropFilter.h>
#import <MTGPUImage/GPUImageGrayscaleFilter.h>
#import <MTGPUImage/GPUImageTransformFilter.h>
#import <MTGPUImage/GPUImageChromaKeyBlendFilter.h>
#import <MTGPUImage/GPUImageHazeFilter.h>
#import <MTGPUImage/GPUImageLuminanceThresholdFilter.h>
#import <MTGPUImage/GPUImagePosterizeFilter.h>
#import <MTGPUImage/GPUImageBoxBlurFilter.h>
#import <MTGPUImage/GPUImageAdaptiveThresholdFilter.h>
#import <MTGPUImage/GPUImageUnsharpMaskFilter.h>
#import <MTGPUImage/GPUImageBulgeDistortionFilter.h>
#import <MTGPUImage/GPUImagePinchDistortionFilter.h>
#import <MTGPUImage/GPUImageCrosshatchFilter.h>
#import <MTGPUImage/GPUImageCGAColorspaceFilter.h>
#import <MTGPUImage/GPUImagePolarPixellateFilter.h>
#import <MTGPUImage/GPUImageStretchDistortionFilter.h>
#import <MTGPUImage/GPUImagePerlinNoiseFilter.h>
#import <MTGPUImage/GPUImageJFAVoronoiFilter.h>
#import <MTGPUImage/GPUImageVoronoiConsumerFilter.h>
#import <MTGPUImage/GPUImageMosaicFilter.h>
#import <MTGPUImage/GPUImageTiltShiftFilter.h>
#import <MTGPUImage/GPUImage3x3ConvolutionFilter.h>
#import <MTGPUImage/GPUImageEmbossFilter.h>
#import <MTGPUImage/GPUImageCannyEdgeDetectionFilter.h>
#import <MTGPUImage/GPUImageThresholdEdgeDetectionFilter.h>
#import <MTGPUImage/GPUImageMaskFilter.h>
#import <MTGPUImage/GPUImageHistogramFilter.h>
#import <MTGPUImage/GPUImageHistogramGenerator.h>
#import <MTGPUImage/GPUImagePrewittEdgeDetectionFilter.h>
#import <MTGPUImage/GPUImageXYDerivativeFilter.h>
#import <MTGPUImage/GPUImageHarrisCornerDetectionFilter.h>
#import <MTGPUImage/GPUImageAlphaBlendFilter.h>
#import <MTGPUImage/GPUImageNormalBlendFilter.h>
#import <MTGPUImage/GPUImageNonMaximumSuppressionFilter.h>
#import <MTGPUImage/GPUImageRGBFilter.h>
#import <MTGPUImage/GPUImageMedianFilter.h>
#import <MTGPUImage/GPUImageBilateralFilter.h>
#import <MTGPUImage/GPUImageCrosshairGenerator.h>
#import <MTGPUImage/GPUImageToneCurveFilter.h>
#import <MTGPUImage/GPUImageNobleCornerDetectionFilter.h>
#import <MTGPUImage/GPUImageShiTomasiFeatureDetectionFilter.h>
#import <MTGPUImage/GPUImageErosionFilter.h>
#import <MTGPUImage/GPUImageRGBErosionFilter.h>
#import <MTGPUImage/GPUImageDilationFilter.h>
#import <MTGPUImage/GPUImageRGBDilationFilter.h>
#import <MTGPUImage/GPUImageOpeningFilter.h>
#import <MTGPUImage/GPUImageRGBOpeningFilter.h>
#import <MTGPUImage/GPUImageClosingFilter.h>
#import <MTGPUImage/GPUImageRGBClosingFilter.h>
#import <MTGPUImage/GPUImageColorPackingFilter.h>
#import <MTGPUImage/GPUImageSphereRefractionFilter.h>
#import <MTGPUImage/GPUImageMonochromeFilter.h>
#import <MTGPUImage/GPUImageOpacityFilter.h>
#import <MTGPUImage/GPUImageHighlightShadowFilter.h>
#import <MTGPUImage/GPUImageFalseColorFilter.h>
#import <MTGPUImage/GPUImageHSBFilter.h>
#import <MTGPUImage/GPUImageHueFilter.h>
#import <MTGPUImage/GPUImageGlassSphereFilter.h>
#import <MTGPUImage/GPUImageLookupFilter.h>
#import <MTGPUImage/GPUImageAmatorkaFilter.h>
#import <MTGPUImage/GPUImageMissEtikateFilter.h>
#import <MTGPUImage/GPUImageSoftEleganceFilter.h>
#import <MTGPUImage/GPUImageAddBlendFilter.h>
#import <MTGPUImage/GPUImageDivideBlendFilter.h>
#import <MTGPUImage/GPUImagePolkaDotFilter.h>
#import <MTGPUImage/GPUImageLocalBinaryPatternFilter.h>
#import <MTGPUImage/GPUImageColorLocalBinaryPatternFilter.h>
#import <MTGPUImage/GPUImageLanczosResamplingFilter.h>
#import <MTGPUImage/GPUImageAverageColor.h>
#import <MTGPUImage/GPUImageSolidColorGenerator.h>
#import <MTGPUImage/GPUImageLuminosity.h>
#import <MTGPUImage/GPUImageAverageLuminanceThresholdFilter.h>
#import <MTGPUImage/GPUImageWhiteBalanceFilter.h>
#import <MTGPUImage/GPUImageChromaKeyFilter.h>
#import <MTGPUImage/GPUImageLowPassFilter.h>
#import <MTGPUImage/GPUImageHighPassFilter.h>
#import <MTGPUImage/GPUImageMotionDetector.h>
#import <MTGPUImage/GPUImageHalftoneFilter.h>
#import <MTGPUImage/GPUImageThresholdedNonMaximumSuppressionFilter.h>
#import <MTGPUImage/GPUImageHoughTransformLineDetector.h>
#import <MTGPUImage/GPUImageParallelCoordinateLineTransformFilter.h>
#import <MTGPUImage/GPUImageThresholdSketchFilter.h>
#import <MTGPUImage/GPUImageLineGenerator.h>
#import <MTGPUImage/GPUImageLinearBurnBlendFilter.h>
#import <MTGPUImage/GPUImageGaussianBlurPositionFilter.h>
#import <MTGPUImage/GPUImagePixellatePositionFilter.h>
#import <MTGPUImage/GPUImageTwoInputCrossTextureSamplingFilter.h>
#import <MTGPUImage/GPUImagePoissonBlendFilter.h>
#import <MTGPUImage/GPUImageMotionBlurFilter.h>
#import <MTGPUImage/GPUImageZoomBlurFilter.h>
#import <MTGPUImage/GPUImageLaplacianFilter.h>
#import <MTGPUImage/GPUImageiOSBlurFilter.h>
#import <MTGPUImage/GPUImageLuminanceRangeFilter.h>
#import <MTGPUImage/GPUImageDirectionalNonMaximumSuppressionFilter.h>
#import <MTGPUImage/GPUImageDirectionalSobelEdgeDetectionFilter.h>
#import <MTGPUImage/GPUImageSingleComponentGaussianBlurFilter.h>
#import <MTGPUImage/GPUImageThreeInputFilter.h>
#import <MTGPUImage/GPUImageFourInputFilter.h>
#import <MTGPUImage/GPUImageWeakPixelInclusionFilter.h>
#import <MTGPUImage/GPUImageFASTCornerDetectionFilter.h>
#import <MTGPUImage/GPUImageMovieComposition.h>
#import <MTGPUImage/GPUImageColourFASTFeatureDetector.h>
#import <MTGPUImage/GPUImageColourFASTSamplingOperation.h>
#import <MTGPUImage/GPUImageSolarizeFilter.h>
